[package]
name = "curve25519-dalek-onchain"
version = "0.0.1"
description = "Curve25519 Dalek library split into instructions to fit under compute limits"
authors = [
    "Lawrence Wu <larry.wu@solana.com>",
]
keywords = ["solana"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.7.15"
subtle = { version = "^2.2.1", default-features = false }
zeroize = { version = "1", default-features = false }

